import { QueryClientProvider } from '@tanstack/react-query'
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Toaster } from 'sonner'
import { queryClient } from '../hooks/client'
import './globals.css'

export const metadata: Metadata = {
  title: 'Tootz OKRs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Toaster richColors />
            {children}
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
